### ISSUE TITLE
rescue_from being sent to Rollbar

### ISSUE THREAD

**Issue by magicalbanana** [rollbar/rollbar-gem#668] opened 2018-01-18 14:14 UTC
Does this gem not honor the `rescue_from` method? Because I have it in our code but for some reason, the exception is still being sent to Rollbar.

**Comment by magicalbanana** [comment] 2018-01-22 16:21
Anyone? Been trying to figure this out for over a week now.

**Comment by ArturMoczulski** [comment] 2018-01-22 19:23
@magicalbanana I just investigated this issue. I was NOT able to reproduce the problem. `rescue_from` works as expected in my Rails app and it stops Rollbar gem from sending to Rollbar service.

I'm going to need more details on your situation to help here.

**Comment by magicalbanana** [comment] 2018-01-22 22:17
@ArturMoczulski interesting. Because it does with us though. Try raising a `RoutingError` exception because that's what we are trying to circumvent.

**Comment by ArturMoczulski** [comment] 2018-01-24 01:43
@magicalbanana Thanks for more info. I tried with `RoutingError` and still can't reproduce. Do you think you can do some more debugging on this issue on your side? I'd like to get to the bottom of this and solve the problem for you.

**Comment by magicalbanana** [comment] 2018-02-06 15:13
Hmm, yeah. I'll test it again today. Is there something we need to be aware when testing this on development with Rails?

**Comment by magicalbanana** [comment] 2018-02-06 15:14
Can I have a look at your config for Rollbar on rails?

**Comment by ArturMoczulski** [comment] 2018-02-07 07:40
Sure, although I'm not doing anything special.

`config/initializers/rollbar.rb`
```ruby
Rollbar.configure do |config|
  # Without configuration, Rollbar is enabled in all environments.
  # To disable in specific environments, set config.enabled=false.

  config.access_token = 'eb2561a52efb4d4bba5a1d4b68be13e9'
  
  config.js_enabled = true
  config.js_options = {
    accessToken: '42a651bef0cb4eb5ba47e9a037747604',
    captureUncaught: true,
    payload: {
      environment: 'rollbar-rails-app'
    }
  }

  # Here we'll disable in 'test':
  if Rails.env.test?
    config.enabled = false
  end

  ...

  config.environment = ENV['ROLLBAR_ENV'].presence || Rails.env
end
```

**Comment by ArturMoczulski** [comment] 2018-02-15 02:01
I'm closing this for now. Feel free to reopen once you get more details on your issue.

**Closed by ArturMoczulski** 2018-02-15 02:01 UTC
Labels: question
