### ISSUE TITLE
compability with rspec-rails 3.4 

### ISSUE THREAD

**Issue by suung** [rollbar/rollbar-gem#403] opened 2016-03-17 01:51 UTC
after updating, in ruby 2.1.5 to rspec-rails 3.4 i get and undefined method split for nil due to rake_version becoming nil.

i investigated a bit, i think it has to be 

```
::Rake::VERSION
```
/lib/rollbar/rake.rb

with :: in the in beginning
in #

**Comment by suung** [comment] 2016-03-17 01:52
i would be happy if we could solve this together :)

**Comment by jondeandres** [comment] 2016-03-17 09:23
Hey @suung, that is resolved in last version of the gem.

By the way, we are upgrading rspec to 3.4 in this PR https://github.com/rollbar/rollbar-gem/pull/402.

**Comment by suung** [comment] 2016-03-17 10:52
hey okay, cool, i will update, thanks!

**Closed** 2016-03-17 10:52 UTC

**Comment by suung** [comment] 2016-03-17 11:29
sorry @jondeandres maybe im dumb, but just updating rollbar doesnt work. i have 2.2.1. what is the latest stable with the fix?

**Comment by jondeandres** [comment] 2016-03-17 11:52
@suung I couldn't reproduce this problem. Can you give us more details about it? You can paste here the steps you are following.

Thanks.

**Comment by suung** [comment] 2016-03-17 17:55
hey @jondeandres 

sorry for the delay.
not sure, what steps i could show you

but i think this helps:

```
$ rspec

[26, 35] in /home/chris/.rvm/gems/ruby-2.1.5@[CENSORED]/gems/rollbar-2.2.1/lib/rollbar/rake.rb
   26:     end
   27: 
   28:     def self.rake_version
   29: 	require 'byebug'
   30: debugger
=> 31:       if Object.const_defined?('RAKEVERSION')
   32:         return RAKEVERSION
   33:       elsif Rake.const_defined?('VERSION')
   34:         return Rake::VERSION
   35:       end
(byebug) Rake::VERSION
*** NameError Exception: uninitialized constant Rollbar::Rake::VERSION

nil
(byebug) ::Rake::VERSION
"11.1.1"
(byebug) 
```

**Comment by jondeandres** [comment] 2016-03-17 17:57
Hi @suung, yes, in 2.2.1 that is broken since Ruby tries to get `Rollbar::Rake::VERSION` instead of `Rake::VERSION`. This is fixed in lasts versions of the gem. Upgrade to 2.8.3 and you should not see that error.

**Comment by suung** [comment] 2016-03-17 18:01
thanks!

now i get this 

```
/home/chris/code/[]/config/initializers/rollbar.rb:2:in `<top (required)>': undefined method `configure' for Rollbar:Module (NoMethodError)
```

but i can probably figure out my way from here

**Comment by jondeandres** [comment] 2016-03-17 18:02
@suung can you give us more details? your problem is using Rollbar in a Rails project?

**Comment by suung** [comment] 2016-03-17 18:13
@jondeandres i am upgrading to rspec 3.4 in a rails project, that is already using rollbar.

**Comment by jondeandres** [comment] 2016-03-17 18:14
oh...ok. what rails version? are you using rspec-rails? Do you `require 'rollbar'` in your rollbar initializer?

**Comment by suung** [comment] 2016-03-17 18:19
i require rollbar/rails, let me try

**Comment by suung** [comment] 2016-03-17 18:19
yes, i have to require rollbar

**Comment by suung** [comment] 2016-03-17 18:21
thanks @jondeandres. i am really convinced of you guys now :) @

**Comment by suung** [comment] 2016-03-17 18:22
when i come to barcelona, i buy you a beer

**Comment by jondeandres** [comment] 2016-03-17 18:22
Thanks! :beers: !!
