### ISSUE TITLE
Rollbar.JS exceptions not reported if Rails server is down

### ISSUE THREAD

**Issue by AndreiRailean** [rollbar/rollbar-gem#661] opened 2017-12-22 04:20 UTC
It appears that If server goes down or not accessible to the user for some reason and there are exceptions in browser, these don't appear to be reported even though browser->rollbar network connection is still good.

For better context, we're dealing with a rich page app that after booting only talks to the server's REST apis so would be up in the browser even if Rails is down.

Is this behaviour by design?

**Comment by rokob** [comment] 2017-12-22 06:26
No this is not by design, the rollbar.js library should operate independently of the gem. Are you using the gem to inject the rollbar.js snippet into your views or are you doing that directly?

**Comment by ArturMoczulski** [comment] 2018-02-22 01:30
@AndreiRailean I wasn't able to reproduce the problem. I confirmed that js exceptions are still reported to Rollbar after the Rails server is down. Do you think you can do more debugging on your side?

**Comment by rivkahstandig3636** [comment] 2018-02-28 15:40
Closing as we are not able to reproduce the issue.

**Closed by rivkahstandig3636** 2018-02-28 15:40 UTC
Labels: bug, rails
