### ISSUE TITLE
ActiveJob exceptions not being reported(rails 5 final)

### ISSUE THREAD

**Issue by plentz** [rollbar/rollbar-gem#497] opened 2016-07-13 18:59 UTC
The same exceptions are being reported to newrelic

``` ruby
class ApplicationJob < ActiveJob::Base
  include Rollbar::ActiveJob
```

``` ruby
class CreateTenantJob < ApplicationJob
```

`rollbar (2.12.0)`

**Comment by jondeandres** [comment] 2016-07-13 22:01
@plentz have you tried including `Rollbar::ActiveJob` in `CreateTenantJob` ?

**Comment by plentz** [comment] 2016-07-14 15:34
@jondeandres adding including `Rollbar::ActiveJob` in `CreateTenantJob` worked. but it shouldn't be necessary, right?

**Comment by jondeandres** [comment] 2016-07-14 15:34
@plentz it wouldn't be needed not. Can you check if your job is being loaded before `ApplicationJob`?

**Comment by plentz** [comment] 2016-07-14 21:29
if `CreateTenantJob` extends `ApplicationJob`, is it even possible?

**Comment by jondeandres** [comment] 2016-07-18 11:29
@plentz let me check this and we'll reach you here

**Comment by jondeandres** [comment] 2016-07-20 04:04
Hi @plentz, we've tried to reproduce your problem. I've set a job inheriting from `ApplicationJob` and using `include Rollbar::ActiveJob` in `ApplicationJob`.

Everything worked as expected. I'm wondering there is something we are missing, maybe in your config or something else. Could you try something? Just raise a known exception in the `perform` method in your job and check if it's being reported or not.

**Comment by plentz** [comment] 2016-07-21 21:43
If I include `Rollbar` directly at the job class, works. Including it @ `ApplicationJob`, not.

Maybe could be something in our `Gemfile`? One thing that I think can be interfering in this is `gem 'newrelic_rpm'`. What do you think?

**Comment by jondeandres** [comment] 2016-07-22 05:37
@plentz I don't think there is nothing related to newrelic_rpm.

Did you try with another exception? Just doing:

```ruby
def perform
  raise StandardError.new
end
```

And check if this works.

**Comment by jessewgibbs** [comment] 2016-08-01 18:46
@plentz have you had a chance to try this out?

**Comment by plentz** [comment] 2016-09-28 14:01
@jessewgibbs @jondeandres same thing. If I include directly @CreateTenantJob, it works. including only @ ApplicationJob not.

```
class CreateTenantJob < ApplicationJob
  #include Rollbar::ActiveJob
  queue_as :default

  def perform(foo, bar, baz)
    raise StandardError.new
  end
end
```

**Comment by rivkahstandig3636** [comment] 2018-05-23 11:26
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Closed by rivkahstandig3636** 2018-05-23 11:26 UTC
Labels: bug, pull-requests-encouraged, rails
