### ISSUE TITLE
Rollbar-gem does not attach JS snippet when secure_headers gem used.

### ISSUE THREAD

**Issue by maszuDEV** [rollbar/rollbar-gem#796] opened 2018-12-11 10:36 UTC
Hi everyone,

I came across the following problem:

When I try to use both Rollbar-gem and Secure Headers together, rollbar-gem does not attach js snippet (Rollbar.js). When I remove Security Headers - everything is ok. There is no error at all. 

So far, I have not been able to find the cause and have not found any working solution. 
Did any of you have a similar problem?

```
My stack:
Ruby: 2.3.1
Rails: 5.2.1
Rollbar-gem: 2.18.0
Secure Headers: 6.0.0 
```

**Comment by jessewgibbs** [comment] 2018-12-11 22:19
@maszuDEV thanks for bringing this to our attention.

@ArturMoczulski can you investigate?

**Comment by ArturMoczulski** [comment] 2019-01-03 10:43
Thanks for reporting @maszuDEV however I am not able to reproduce the problem. I've just created a new `rails:5.2.1` app with `rollbar-gem:v1.8.2` and `secure_headers:6.0.0` on `ruby:2.3.1`. Errors are being reported to Rollbar as expected. 

I'm closing the issue for now, but can you tell me more about your `rollbar-gem` configuration? I'll reopen once we get to the bottom of what is happening in your app.

**Closed by ArturMoczulski** 2019-01-03 10:43 UTC
