### ISSUE TITLE
Gem failsafe error about connecting to DB

### ISSUE THREAD

**Issue by jessewgibbs** [rollbar/rollbar-gem#620] opened 2017-08-07 23:41 UTC
Details in https://app.clubhouse.io/rollbar/story/22078/gem-failsafe-error-about-connecting-to-db

**Comment by rivkahstandig3636** [comment] 2018-02-28 15:36
Closing this issue as we are unable to reproduce it.

**Comment by sdhull** [comment] 2019-03-15 17:38
We've actually been seeing this intermittently in production as well. The primary issue is that the error has basically no information. I have no idea how to go about debugging this. What's a guy gotta do to get backtrace?

`Failsafe from rollbar-gem. ActiveRecord::ConnectionTimeoutError: \"could not obtain a connection from the pool within 5.000 seconds (waited 5.000 seconds); all pooled connections were in use\" in /app/vendor/bundle/ruby/2.5.0/gems/activerecord-5.2.2.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:201:in 'block in wait_poll': build_item in exception_data'`

**Comment by brianr** [comment] 2019-03-15 17:47
Thanks @sdhull .

@waltjones Any ideas on 1) what might cause this situation, and 2) how rollbar-gem can better handle it?

**Comment by waltjones** [comment] 2019-03-15 17:50
@sdhull I'll take a look to see if more diagnostic info can be provided in these failsafe conditions.

@brianr It looks like the original error is the connection pool is exhausted, with unknown root cause. It looks like rollbar-gem should provide more info on failsafe conditions regardless of what error got us there.

**Comment by brianr** [comment] 2019-03-15 17:54
@waltjones 👍 

The other thing I'm wondering is whether this situation can result in a more positive outcome than a failsafe. I assume the db connection attempt is happening when rollbar-gem is trying to get the person data, or maybe in "custom_data_fn" or something like that. If that happens, I'd think we can still report the original stack trace and the contextual data that we are able to get; we just won't have the person data/whatever failed to build.

**Comment by waltjones** [comment] 2019-03-15 18:03
@brianr Good idea.

**Comment by sdhull** [comment] 2019-03-15 18:17
Super impressed how responsive you guys are. Thanks! Looking forward to seeing this move

**Comment by rokob** [comment] 2019-03-15 19:20
Usually by the time we get to a failsafe it is because we tried making a payload with some information and even that failed. If there is an exception in say the person function we should already just ignore it and try to move on with that blank.

**Comment by waltjones** [comment] 2019-03-15 20:02
@sdhull can you bundle with branch `wj-failsafe`? This isn't a final fix, but should allow you to get the report for the original exception. If the original non-rollbar exception is also `ActiveRecord::ConnectionTimeoutError` that would be interesting to know.

**Closed** 2019-03-18 16:52 UTC
Labels: bug
