### ISSUE TITLE
No error logs in development

### ISSUE THREAD

**Issue by BScharbau** [rollbar/rollbar-gem#590] opened 2017-04-25 06:01 UTC
Hi guys,

I'm working on a project and we want to report our errors in production via Rollbar, so we are utilizing the rollbar-gem. In production, everything works as expected.

In development, we want to disable reporting to Rollbar. We can achieve this by adding
```
config.enabled = false unless Rails.env.production?
```
in `config/initializers/rollbar.rb`, however, doing so results in destroying all error logging in development, i.e. I don't get any stack traces, code fail locations, etc., neither to console, nor to `log/development.log`, nor displayed on the page. This makes bugfixing a real pain in the ass.

Is this a known issue? Did I misconfigure something?

**Comment by jondeandres** [comment] 2017-04-26 15:11
Hi @BScharbau,

thanks for reporting this issue. I'd say this is an unexpected behavior but I'm not sure this is related to our code.

It's true that when we send messages to the logger we skip them in case the configuration is not enabled https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/logger_proxy.rb#L26.

We use this logger for the messages we want to log and it's just a proxy to `Rollbar::Configuration#logger`, which is by default `Logger.new(STDERR)` or `Rails.logger` in case of Rails.

So, your logging in your project should work as usual even having the gem disabled. Also, in the middlewares we add to the chain we are always re-raising the exceptions, so the behavior should be fine.

This may be a bug related to our Rails integration, but we'd need more information to debug this.

**Comment by coryvirok** [comment] 2017-06-08 01:05
@BScharbau, did Jon's info help you figure this out? Are you still experiencing this?

**Comment by pixind** [comment] 2017-06-09 12:59
Hi there, I can confirm that I'm experiencing the exact same case that @BScharbau is reporting.

The only way to get back the "normal" stack trace is by commenting the gem while coding, and re bundling... which is kinda of a pain.

Any information that I can provide to help you guys figuring this out, I'd be happy to give :)

Thanks!

**Comment by jondeandres** [comment] 2017-06-12 11:40
@pixind can you in a rails console just write `Rails.logger` and paste here the output?

Thanks.

**Comment by pixind** [comment] 2017-06-18 10:09
Sure :)
~~~
[1] pry(main)> Rails.logger
=> #<ActiveSupport::Logger:0x007fa9f83d0ca8
 @default_formatter=#<Logger::Formatter:0x007fa9f83d0c08 @datetime_format=nil>,
 @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x007fa9f9902090 @datetime_format=nil>,
 @level=0,
 @local_levels=#<Concurrent::Map:0x007fa9f83d0aa0 entries=0 default_proc=nil>,
 @logdev=
  #<Logger::LogDevice:0x007fa9f83d0bb8
   @dev=#<File:/Users/pixind/projects/project-name/log/development.log>,
   @filename=nil,
   @mon_count=0,
   @mon_mutex=#<Thread::Mutex:0x007fa9f83d0b40>,
   @mon_owner=nil,
   @shift_age=nil,
   @shift_period_suffix=nil,
   @shift_size=nil>,
 @progname=nil>
~~~

**Comment by jondeandres** [comment] 2017-06-19 10:59
Hi @pixind, thanks. I've tried to reproduce this and I didn't have success. Which Rails version are you using?

Can you run `rake middleware` and paste us the output?

Thanks.

**Comment by pixind** [comment] 2017-06-29 09:02
Hey, sorry about the delay.. I was out and without internet access ( that sort of bless/curse) for a couple of days.
Versions are:

`ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin16]`
`Rails 5.0.2`

### Middleware
~~~
use Rack::Cors
use Rack::Sendfile
use ActionDispatch::Static
use ActionDispatch::Executor
use ActiveSupport::Cache::Strategy::LocalCache::Middleware
use Rack::Runtime
use Rack::MethodOverride
use ActionDispatch::RequestId
use Sprockets::Rails::QuietAssets
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use WebConsole::Middleware
use ActionDispatch::DebugExceptions
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::Migration::CheckPending
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use Warden::Manager
use CatchJsonParseErrors
run MyApp::Application.routes
~~~

**Comment by pixind** [comment] 2017-06-29 09:07
Just in case you're wondering what that CatchJsonParse errors does

~~~
class CatchJsonParseErrors
  def initialize(app)
    @app = app
  end

  def call(env)
    begin
      @app.call(env)
    rescue ActionDispatch::ParamsParser::ParseError => error
      if env['HTTP_ACCEPT'] =~ %r{/application\/json/}
        error_output = "There was a problem in the JSON you submitted: #{error}"
        return [
          400, { 'Content-Type' => 'application/json' },
          [{ status: 400, error: error_output }.to_json]
        ]
      else
        raise error
      end
    end
  end
end
~~~

**Comment by pixind** [comment] 2017-07-17 09:53
Hi guys, @jondeandres, do you have any news or even some monkey patch/workaround related to this? Anything else I can do in order to help?

I still having this error, updated to 2.15.0 but issue persists.

Cheers.

**Comment by rokob** [comment] 2017-07-17 17:32
Creating a fresh Rails app, adding the Rollbar gem and disabling it causes exceptions to still print to the console and to log/development.log. Enabling Rollbar causes output to show up in the console and for items to be reported to Rollbar. Let me see if I can try something else.

**Comment by CodeMonkeyKevin** [comment] 2017-09-05 15:59
I'm also getting the same issue. I had to scope Rollbar gem to production only to get around this issue in development.

**Comment by rivkahstandig3636** [comment] 2018-05-23 11:29
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Closed by rivkahstandig3636** 2018-05-23 11:29 UTC
Labels: bug

**Comment by dechimp** [comment] 2020-07-08 15:30
I came here because calls to ```Rollbar.error```, ```Rollbar.warn```, etc. is silent in the Rails console if you have Rollbar disabled.  Natural errors show up, just not these deliberate calls to Rollbar.  

Currently to bypass this, I am monkey patching Rollbar, but of course would prefer not to. Any ideas on what to do about this?  Thanks in advance.

**Comment by dechimp** [comment] 2020-07-08 16:01
I see that this has been discussed at length and even a feature was added to address the issue https://github.com/rollbar/rollbar-gem/issues/813

Just now, I set this in my config:
```
config.enabled = true
config.log_payload = false
config.transmit = Rails.env.production? || Rails.env.staging?
```
`log_payload` is too verbose for me as a default, but at least I now get a simple error message in the application output.

**Comment by waltjones** [comment] 2020-07-08 16:13
@dechimp The `config.transmit` options was added later than when this issue was closed. If I understand your comments, it is the option that solves your issue. (Fully process the item, but don't send.)

**Comment by dechimp** [comment] 2020-07-08 17:17
@waltjones Yes thanks. So far, it seems to be what I need.
