### ISSUE TITLE
Sidekiq + Rollbar + DNS failure

### ISSUE THREAD

**Issue by jalada** [rollbar/rollbar-gem#577] opened 2017-03-22 09:07 UTC
I had a situation where DNS resolution on my server failed and that seemed to trigger a cascade of Sidekiq jobs; because the Rollbar reporting job would fail to resolve `api.rollbar.com`, the failsafe would queue up another job, along with the existing retrying job, resulting in lots of lines like:

```
Mar 21 09:04:17 xxx production.log:  E, [2017-03-21T09:04:17.550745 #303] ERROR -- : [Rollbar] Reporting internal error encountered while sending data to Rollbar.
Mar 21 09:04:17 xxx production.log:  I, [2017-03-21T09:04:17.554127 #303]  INFO -- : [Rollbar] Sending item
Mar 21 09:04:17 xxx production.log:  E, [2017-03-21T09:04:17.556616 #303] ERROR -- : [Rollbar] Error processing the item: SocketError, Failed to open TCP connection to api.rollbar.com:443 (getaddrinfo: No address associated with hostname). Item: {"access_token"=>"xxx", "data"=>{:timestamp=>1490087057, :environment=>"production", :level=>"error", :language=>"ruby", :framework=>"Rails: 5.0.1", :server=>{:host=>"xxx", :root=>"/var/www/xxx/releases/xxx", :pid=>303}, :notifier=>{:name=>"rollbar-gem", :version=>"2.14.0"}, :body=>{:trace_chain=>[{:frames=>[{:filename=>"/var/www/xxx/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb", :lineno=>26, :method=>"block in safe_thread"}, {:filename=>"/var/www/xxx/shared/bundle/ruby/2.4.0/gems/sidekiq-4.2.9/lib/sidekiq/util.rb", :lineno=>17, :method=>"watchdog"}
```

I'm trying to understand if this is a bug, or a mis-configuration on our part. I've attempted to mitigate it happening again by setting the Rollbar Sidekiq options to never retry. Is there anything else I need to change?

**Comment by jalada** [comment] 2017-03-23 09:42
I think I've worked out why this is happening:

1. Exception is raised, causing a notification job to be queued.
2. `process_from_async_handler` tries to report the notification, but fails, so `report_internal_error` is called.
3. `report_internal_error` tries to build a new item to send immediately, but that also fails, triggering `send_failsafe`.
4. `send_failsafe` queues up another asynchronous notification job.
5. Repeat step 2.

**Comment by ilyapoz** [comment] 2017-03-23 21:41
I had the exact same incident a couple of days ago, Mar 22, 4:24 UTC
At 5:23 my redis server's memory was depleted so sidekiq lost connection and no events were actually submitted to rollbar, otherwise that would devastate my plan's monthly limit :)

rollbar api status page http://status.rollbar.com/#week indicates no downtimes so I have to assume this is a coincidence and my hosting provider had some dns problems too.

An analogous issue is reported in #542

**Comment by ilyapoz** [comment] 2017-03-28 12:19
Based on code (Rollbar.silence) this should not happen. I think we have to try to reproduce this somehow.

**Comment by coryvirok** [comment] 2017-06-08 01:07
Thanks for the report. @rokob can you take a look at this?

**Comment by rivkahstandig3636** [comment] 2018-05-23 11:29
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Closed by rivkahstandig3636** 2018-05-23 11:29 UTC
Labels: bug, question, sidekiq
