### ISSUE TITLE
DNS Timeout Issues

### ISSUE THREAD

**Issue by rebelweb** [rollbar/rollbar-gem#542] opened 2016-11-08 16:27 UTC
I am experiencing an issue with gem when reporting using sidekiq. What happens if DNS is not responding properly or configured at all (I have had both happen),  it causes a timeout issue, and tries to resend the issue again, but it appears it is now sending 2 issues the Timeout issue and the original issue. This issue keeps growing until disk space or memory is fully consumed. 

I have included basic reproduction steps. If you need more information or help let me know I would be glad to help.

## Reproduction Steps
1. basic rails app with sidekiq & rollbar configured
2. Configure the server with no DNS
3. Throw an error in the Rails App
4. Issue with start growing.

**Comment by jondeandres** [comment] 2016-11-08 21:32
Hi @rebelweb, thanks for opening the issue with the detailed reproduction steps. We'll try to do something on this soon. We'd need to make our reporting job configurable so users can configure to report those errors or not.

You can for now monkey patch `Rollbar::Delay::Sidekiq#perform`. You can rescue all exceptions when calling the original method, and then inspect the received args. Identify if the job is `Rollbar::Delay::Sidekiq` and then swallow the exception.

Let me know if this works for you. Thanks again.

**Comment by rivkahstandig3636** [comment] 2018-05-23 11:27
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Closed by rivkahstandig3636** 2018-05-23 11:27 UTC
Labels: bug
