### ISSUE TITLE
Rollbar hits "stack level too deep" when context contains ActiveRecord class

### ISSUE THREAD

**Issue by halacheva** [rollbar/rollbar-gem#545] opened 2016-11-10 10:28 UTC
Hey, I found out that Rollbar seems to loop endlessly when an exception report is sent with context that contains ActiveRecord class. 

I am using DelayedJob and encountered the issue when the jobs started to hang and take up the whole memory. The jobs were failing and got stuck during attempt to send report to Rollbar. It turned out that a failed job scheduled on a ActiveRecord class method like this `Person.delay.some_class_method` would hang, but a failed job scheduled on an instance method like this `some_person.delay.some_instance_method` would go smoothly. I'd like to send in the context the details of the handler of the delayed job. This is how I found out that when the handler details contain the ActiveRecord class Rollbar goes into an endless loop.

I managed to reproduce the problem without DelayedJob and here are few examples that I experimented with. 
```Ruby
# successful
def test_string
  context = { target: 'string' }

  exception = StandardError.new 'fake error string'
  Rollbar.error exception, context
end

# successful
def test_instance
  context = { target: Person.first }

  exception = StandardError.new 'fake error instance'
  Rollbar.error exception, context
end

# successful
def test_simple_class
  context = { target: NonActiveRecordClass }

  exception = StandardError.new 'fake error simple class'
  Rollbar.error exception, context
end

# failed, gets 'stack level too deep'
def test_activerecord_class
  context = { target: Person }

  exception = StandardError.new 'fake error ActiveRecord class'
  Rollbar.error exception, context
end
```

The problem seems to be only with ActiveRecord classes. I managed to track it down to here: https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/notifier.rb#L146

I'm using the latest version of Rollbar v.2.13.3

**Comment by jondeandres** [comment] 2016-11-28 14:17
Hi @halacheva, sorry for the delay. An issue like this has been reported before, and I concluded that the problem is between `ActiveSupport::JSON` and `ActiveRecord::Base`. We'll try to find a workaround for this, but I guess, for now, the recommended use is just try to avoid passing `ActiveRecord::Base` subclasses.

We'll reach you here when we find something. Thank you very much @halacheva!

**Comment by rivkahstandig3636** [comment] 2018-05-23 11:28
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Closed by rivkahstandig3636** 2018-05-23 11:28 UTC
Labels: bug

**Comment by simonc** [comment] 2018-11-13 14:17
Hi. This still an issue 😊
