### ISSUE TITLE
Two errors produced from DelayedJob; one with stack trace, one without.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [rollbar/rollbar-gem#677] opened 2018-02-01 21:35 UTC
Hello, we're noticing some peculiar behavior where an uncaught exception from a DelayedJob produces two different errors in our Rollbar logs; one has a stack trace, one does not. The Rollbar support team directed me here to raise an issue on the repo.

We have two examples that we could link to, please message me privately at andrewsmith@alumni.stanford.edu for the links. I'll try to show as much detail here though.

**With the stack trace**

<img width="1225" alt="screen shot 2018-02-01 at 1 22 08 pm" src="https://user-images.githubusercontent.com/5187404/35704036-f6b38df2-0752-11e8-89d2-c2fc9c0b0cc4.png">

Note that this correctly includes the `ActiveRecord::RecordInvalid` error.

Stack traces do show up in the occurrences:

<img width="1236" alt="screen shot 2018-02-01 at 1 22 21 pm" src="https://user-images.githubusercontent.com/5187404/35704086-19ff6452-0753-11e8-8913-51d980a17cbc.png">

**Without the stack trace**

<img width="1227" alt="screen shot 2018-02-01 at 1 19 45 pm" src="https://user-images.githubusercontent.com/5187404/35703966-bed8a0c0-0752-11e8-90f2-a8652c823111.png">

Note how there's no interpretation of project vs. gem stack traces, etc. Also there's no inclusion of the error name.

No stack trace is provided in the occurrences tab either:

<img width="1223" alt="screen shot 2018-02-01 at 1 21 16 pm" src="https://user-images.githubusercontent.com/5187404/35704008-de8ed68c-0752-11e8-9239-5b3bbbcde0c7.png">

**Application job definition**

Here's our error handling within our jobs:

```ruby
class ApplicationJob < ActiveJob::Base
  def initialize(*args)
    super
    @context = {}
  end

  rescue_from(StandardError) do |e|
    context[:job] = self.class.name
    Rollbar.scope! data: context
    raise e
  end
  ...
end
```

Let us know if you need any more info!

**Comment by ArturMoczulski** [comment] 2018-02-07 09:50
@AndrewSouthpaw I sent you an email to take a look at your examples.

**Comment by ArturMoczulski** [comment] 2018-02-08 00:53
@AndrewSouthpaw I tried but wasn't able to reproduce the problem on my own. I'll wait to get the examples from you.

**Comment by rivkahstandig3636** [comment] 2018-02-28 15:42
Closing as we are not able to reproduce the issue.

**Comment by AndrewSouthpaw** [comment] 2018-03-01 17:06
@rivkahstandig3636 I did send Artur the examples, and didn't hear back after that. Was the repro unsuccessful?

**Comment by rivkahstandig3636** [comment] 2018-03-01 17:59
Ah I appear to have misunderstood from @ArturMoczulski's comment. @ArturMoczulski should this be reopened?

**Comment by ArturMoczulski** [comment] 2018-05-17 03:44
@AndrewSouthpaw @rivkahstandig3636 sorry for confusion. yes, this needs to be reopened and still addressed. I'm putting it into the `v2.17.0` milestone.

**Comment by jondeandres** [comment] 2018-09-19 12:40
Hey @AndrewSouthpaw, sorry for the delay. We were wondering if you are using the rails logger integration we have, something like this in one initializer:

```
Rails.logger.extend(ActiveSupport::Logger.broadcast(Rollbar::Logger.new))
```
Also, these items are happening in development or a production environment?

**Comment by jessewgibbs** [comment] 2018-09-21 01:23
I'm going to close this pending feedback from @AndrewSouthpaw.

**Closed by jessewgibbs** 2018-09-21 01:23 UTC
Labels: bug
