### ISSUE TITLE
Can't Call Configure Multiple Times

### ISSUE THREAD

**Issue by ajtran** [rollbar/rollbar-gem#767] opened 2018-08-07 22:25 UTC
internal - https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/488687/conversations/17885869159

a user is having this issue:

"This is a small ruby project where we want to also use Rollbar for our error reporting. This configuration is working for me, but a second call to it (such as in a debugging/pry session, after initialization) doesn't have any impact"

code to reproduce what is happening
```
[9] pry > Rollbar.configure do |config|
[10] pry * config.access_token = "POST_SERVER_ITEM_ACCESS_TOKEN" 
[10] pry * end; 
[11] pry > Rollbar.configuration.access_token
=> nil
```

**Comment by ChaoticBoredom** [comment] 2018-08-07 23:09
I was the person originating the issue, please let me know if there's anything else I can do to help with resolving this. :)

**Comment by brianr** [comment] 2018-08-08 01:24
@ChaoticBoredom If you know that you are calling it a second time, you can use `Rollbar.reconfigure` instead. Will that work for your situation?

**Comment by brianr** [comment] 2018-08-08 01:26
The other thing you can do, if you just want to add custom data to any future payloads, is use `Rollbar.scope!` or a `Rollbar.scoped` block - that's designed for this purpose. The docs attempt to explain this at https://docs.rollbar.com/docs/ruby#section-the-scope

**Comment by ChaoticBoredom** [comment] 2018-08-08 15:31
@brianr I was explicitly using it in a debugging context here, and could not assign any values using `configure`. Is this known and expected? I didn't see anything about `reconfigure` in the docs when I was trying to understand what was happening, and in a Rails project, this worked as is, no different commands needed.

**Comment by ArturMoczulski** [comment] 2018-08-29 13:13
I'm not able to reproduce this at all. @ChaoticBoredom from what I understand this is not currently a blocking problem for your development, right? If so, let's reopen this issue when it becomes more problematic or when there is more information.

**Closed by ArturMoczulski** 2018-08-29 13:13 UTC
Labels: question
