### ISSUE TITLE
capture RangeError: exceeded available parameter key space error

### ISSUE THREAD

**Issue by kushkella** [rollbar/rollbar-gem#236] opened 2015-04-22 09:36 UTC
I've been seeing that rollbar-gem doesn't capture `RangeError: exceeded available parameter key space` which is generated when there are too many query parameters and Rack::Util fails to parse the query string. For reference:

http://stackoverflow.com/questions/12243694/getting-error-exceeded-available-parameter-key-space
http://stackoverflow.com/questions/26544792/error-exceeded-available-parameter-key-space
https://github.com/rack/rack/issues/318

I'm seeing this error being reported in NewRelic but can't see the same in Rollbar. Thanks!

**Comment by jondeandres** [comment] 2015-04-22 09:39
@kushkella do you know, in rack code, where exactly is raised?

Thanks for this report. We'll try to fix it :smile:

**Comment by kushkella** [comment] 2015-04-22 09:43
Following is the stack trace reported in NewRelic:

```
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 548:in `[]='
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 136:in `normalize_params'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 155:in `normalize_params'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 155:in `normalize_params'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 150:in `normalize_params'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 150:in `normalize_params'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 150:in `normalize_params'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 116:in `block in parse_nested_query'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 113:in `each'
…or/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
utils.rb: 113:in `parse_nested_query'
…/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
request.rb: 369:in `parse_query'
…/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
request.rb: 215:in `POST'
…/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
methodoverride.rb:  39:in `method_override_param'
…/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
methodoverride.rb:  27:in `method_override'
…/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
methodoverride.rb:  15:in `call'
…/bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
runtime.rb:  18:in `call'
…bundle/ruby/2.2.0/gems/rack-1.6.0/lib/rack/
sendfile.rb: 113:in `call'
```

**Comment by jondeandres** [comment] 2015-04-22 09:44
Cool! We'll see what we can do. Thanks!!

**Comment by Crisfole** [comment] 2016-02-01 11:08
Any chance you can also send us the output of `rake middleware`? We suspect what's happening is that the error is occurring sometime between where NewRelic is hooking in, and where Rollbar is hooking in, so New Relic gets an opportunity to report it, but Rollbar doesn't.

**Comment by jondeandres** [comment] 2016-09-16 12:17
@kushkella can we know exactly how is your app setup? Which middleware are you using to report errors to Rollbar? It looks like the order of middlewares is not correct and that error is happening before we can wrap the execution flow in our middleware.

**Comment by jondeandres** [comment] 2016-09-16 12:36
I've been trying to reproduce this with this code:

```ruby
# config.ru

require 'rack/utils'
require 'rollbar'

require './app'

Rollbar.configure do |config|
  config.access_token = '**************'
  config.framework = 'Rack'
  config.enabled = true
  config.environment = 'rack-tests'
end

require 'rollbar/middleware/sinatra'
use Rollbar::Middleware::Sinatra

run App.new


# app.rb
require 'rack/request'

Rack::Utils.key_space_limit = 1

class App
  def call(env)
    request = Rack::Request.new(env)
    request.GET

    [200, {}, ['foo']]
  end
end
```
Running `curl http://localhost:9292\?foo\=bar` I can see the error report in https://rollbar.com/Rollbar/rollbar-gem/items/6842/.

I think what is happening with your configuration is that the Rollbar middleware is after the sendfile middleware. We would need more details about how are you adding the middlewares to the chain.

**Comment by jondeandres** [comment] 2016-09-16 15:21
I'll close this since it's not a problem with the gem itself, but in the order the users add the middleware.

**Closed by jondeandres** 2016-09-16 15:21 UTC
