### ISSUE TITLE
Sending backtrace for messages events

### ISSUE THREAD

**Issue by vikalejo** [rollbar/rollbar-gem#243] opened 2015-05-20 14:12 UTC
We can send the backtrace for no rescued exceptions, using this option in the configuration:
https://github.com/rollbar/rollbar-gem#sending-backtrace-without-rescued-exceptions
`config.populate_empty_backtraces = true`
and that is great :)
What about to do it also for non exceptions issues?, so we can see the backtrace also for ocurrences with just a message like. 
`Rollbar.warning('some message to report')`

**Comment by coryvirok** [comment] 2017-06-08 01:31
@jondeandres what are the next steps for this? Maybe @rokob can take it over?

**Comment by jondeandres** [comment] 2017-06-08 09:54
We can try to make https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/item.rb#L187 to follow the same strategy than in https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/item/backtrace.rb#L83-L99 to get the backtrace.

The problem I see is that we would be sending `trace` or `trace_chain` at the same time than `message`, and as our API says, only one should be sent:

```
// Option 3: "message"
// Only one of "trace", "trace_chain", "message", or "crash_report" should be present.
// Presence of a "message" key means that this payload is a log message.
```

So I think we would need to do few changes in our end to support this.

**Comment by rokob** [comment] 2017-06-20 18:10
This should be fixed by having the backend support both message and trace/trace_chain, and then sending both. Currently one work around is to take the message and add it as the description to the exception in the trace. We could do that with some configuration option until the backend supports both.

**Comment by bdelo** [comment] 2019-04-01 20:46
Looks like this might be duplicate of https://github.com/rollbar/rollbar-gem/issues/568 ?

**Closed** 2024-06-12 18:55 UTC
Labels: enhancement
