### ISSUE TITLE
Expand symlinks for project_gems

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-gem#200] opened 2015-01-15 16:00 UTC
If your project_gems are in a directory that is a symlink, then the paths that end up in `project_package_paths` (which Rollbar.com uses to decide whether frames are in-project) won't match the paths in the stacktrace (which have symlinks expanded).

The fix is probably the call [Pathname.realpath](http://ruby-doc.org/stdlib-1.8.7/libdoc/pathname/rdoc/Pathname.html#method-i-realpath) on each path that's built in this block: ​https://github.com/rollbar/rollbar-gem/blob/master/lib/rollbar/configuration.rb#L137-L145

**Comment by jondeandres** [comment] 2015-01-15 16:05
Good point.

:+1:

**Comment by jondeandres** [comment] 2015-01-16 15:44
@brianr do you have more info about this?

I've tried to reproduce this and I can't. I have a `gems` directory with the `rack` gem inside. I've added this to my Gemfile: gem 'rack', path: './mygems'. And `mygems` is a symlink to `gems`.

I configured Rollbar to have `project_gems = ['rack']` and I've been able to see the expanded rack backtrace: https://rollbar.com/Rollbar/rollbar-gem/items/2092/occurrences/3896374160/

This is using Linux, do you have some more info about the SO reporting this?

**Comment by jondeandres** [comment] 2016-09-16 15:21
I'll close this since I was able to make it work. It may be a OSX issue. Let's close this since seems it's not giving problems.

**Closed by jondeandres** 2016-09-16 15:21 UTC
